### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by ghost**
built-in action quotetalk :  message 中の %(quotemsg)s を amzweb などで生成した文章で置換する。引用表現のような使い方を想定。
build-in action suggest : message に %(suggested)s および %(suggested2)s を埋め込めるよう拡張。

### CODE REVIEW

**Comment by atzm** [comment]
On my environment, flake8 gives following warning:
```
$ flake8 ./amazonas/irchandler/actions.py
./amazonas/irchandler/actions.py:135:13: E126 continuation line over-indented for hanging indent
```
Can you fix it?

**Comment by atzm** [comment]
- `quotetalk` seems keyword version of the `talk` . "quote" is how to use the action you think, but it does not indicate operation of the action, IMHO. So I think it should be renamed to more essential name.
- `quotetalk` action seems returning only 1st valid line of the generated text. But is this correct anytime? User may want to use the full text.
- I think format of the logging on `quotetalk` should be changed because it does not notice to IRC directly unlike the `talk` .

**Comment by atzm** [comment]
About the change for the `suggest` action, I think it's better that the user can choose and extend register names which suggested values are set.

For example, the code of `suggest` action can be changed like:
```
-    return {'suggested': random.choice(result)}
+    def map_registers(candidates, registers):
+        for reg in registers:
+            try:
+                yield reg, candidates.pop()
+            except KeyError:
+                yield reg, ''
+
+    return dict(map_registers(set(result), util.split(conf.get('registers', 'suggested'))))
```

Then the configuration can be:
```
[action:mysuggest]
action    = suggest
registers = suggested1 suggested2 suggested3
message   = Did you mean: %(suggested1)s %(suggested2)s %(suggested3)s
...
```

In this case, it doesn't break compatibility because the default value of `registers` is `suggested` .

Note: using `set.pop()` may keep compatibility for the randomness, but simple sequential mapping may be better than keeping compatibility.

**Comment by ghost** [comment]
Thank you for your comments and proposal. 
I need multiple suggested words as simply.
I'll leave correction to you.

**Comment by atzm** [comment]
Sure.  Will support multiple suggestion and the keyword version of the `talk`.

**Pull request closed without merging**
